Single dimension NumPy Array

In [1]:
!pip install numpy

In [1]:
import numpy as np

In [6]:
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [7]:
type(n1)

numpy.ndarray

# MultiDimension NumPy Array

In [8]:
import numpy as np

In [9]:
n2=np.array([[10,20,30],[10,80,90],[30,60,40]])

In [13]:
print(n2)

[[10 20 30]
 [10 80 90]
 [30 60 40]]


In [14]:
# Note: we use 2 big brackets [[ for 2 dimensional

# initialize NumPy array with Zeroes

In [15]:
import numpy as np

In [27]:
n3=np.zeros((9,9))

In [28]:
print(n3)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# Initialization an array of matrix with full then

In [29]:
import numpy as np

In [31]:
n4=np.full((3,3),9)

In [32]:
print(n4)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


# Initializationn of NumPy array within a range

In [34]:
import numpy as np

In [35]:
# note: we don't need to import numpy all the time

In [37]:
n5=np.arange(10,20)

In [38]:
print(n5)

[10 11 12 13 14 15 16 17 18 19]


# initialization of the NumPy array with the skip numbers

In [41]:
n6=np.arange(1,10,2)

In [42]:
print(n6)

[1 3 5 7 9]


# Initialization NumPy array with the random numbers

In [47]:
n7=np.random.randint(100,1000,10)
print(n7)

[640 515 124 877 783 565 830 325 428 533]


# Initialization of the array shape changes in a fraction of seconds

In [56]:
n8=np.array([[10,20,30],[10,80,90],[30,50,70],[40,70,80]])

In [57]:
n8.shape

(4, 3)

In [58]:
n8.shape=(3,4)
print(n8)

[[10 20 30 10]
 [80 90 30 50]
 [70 40 70 80]]


#Joining NumPy array

In [64]:
a=np.array([10,20,30,40,50,60,70,80,90,40])
b=np.array([70,80,70,90,60,30,10,20,40,70])
np.vstack((a,b))

array([[10, 20, 30, 40, 50, 60, 70, 80, 90, 40],
       [70, 80, 70, 90, 60, 30, 10, 20, 40, 70]])

In [65]:
np.hstack((a,b))

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 40, 70, 80, 70, 90, 60, 30, 10,
       20, 40, 70])

In [66]:
np.column_stack((a,b))

array([[10, 70],
       [20, 80],
       [30, 70],
       [40, 90],
       [50, 60],
       [60, 30],
       [70, 10],
       [80, 20],
       [90, 40],
       [40, 70]])

# NumPy intersection and difference

In [2]:
import numpy as np
x=np.array([10,20,30,40,50,60])

In [4]:
y=np.array([30,50,90,100,120,150])

In [6]:
print(np.intersect1d(x,y))

[30 50]


In [9]:
print(np.setdiff1d(x,y))

[10 20 40 60]


# Addition of NumPy arrays

In [11]:
t=np.array([10,20])
s=np.array([30,40])

In [13]:
np.sum([t,s])

100

In [18]:
np.sum([t,s],axis=1) # when axis is 0, it adds row, and when axis is 1, it adds column.

array([30, 70])

# NumPy array mathematics

In [19]:
p=np.array([10,20,30])

In [20]:
p+1

array([11, 21, 31])

In [21]:
p/2

array([ 5., 10., 15.])

In [22]:
p*2

array([20, 40, 60])

In [23]:
p-2

array([ 8, 18, 28])

# NumPy math functions

In [24]:
nn=np.array([10,20,30,60])

In [25]:
np.mean(nn)

30.0

In [26]:
np.median(nn)

25.0

In [27]:
np.std(nn)

18.708286933869708

# Saving and loadin NumPy array

In [28]:
import numpy as np

In [29]:
n11=np.array([10,20,30,40,50])

In [30]:
np.save('my_name',n11)

In [31]:
np.load('my_name.npy')

array([10, 20, 30, 40, 50])

# Array creation methods

1. Uniform samples

In [32]:
np.random.uniform(5,10,size = 4)

array([8.7542047 , 9.62032877, 8.89252459, 6.98266266])

In [33]:
np.random.uniform(size = 5)

array([0.10285529, 0.35269198, 0.1454928 , 0.01469434, 0.27951891])

Random

In [35]:
np.random.randint(5,10,10) # (low value, high value, number of size)

array([6, 9, 8, 5, 6, 7, 7, 8, 6, 5])

In [37]:
np.random.random(3)

array([0.23126773, 0.01610093, 0.2293318 ])

2. Logspace

In [39]:
np.logspace(0,10,5,base=2)  # 0 is start, 10 is end, 5 is the number of values to be produced

array([1.00000000e+00, 5.65685425e+00, 3.20000000e+01, 1.81019336e+02,
       1.02400000e+03])

3. Identity

In [42]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Array operations

1. Min

In [43]:
arr=np.array([1,1,2,3,4,5,1,6])

In [44]:
np.min(arr)

1

In [45]:
np.max(arr)

6

In [48]:
np.unique(arr, return_counts=True) # it gives the values and how many it is repeated or number of their repeatation

(array([1, 2, 3, 4, 5, 6]), array([3, 1, 1, 1, 1, 1], dtype=int64))

2. Digitize

In [51]:
a=np.array([-0.9,0.5,0.9,1.4,3.6,4.7,5.3]) 
bins=np.array([0,1,2,3])

In [52]:
np.digitize(a,bins)

array([0, 1, 1, 2, 4, 4, 4], dtype=int64)

3. Expanding the dimensions

In [53]:
arr=np.array([8,14,1,8,4,7,5,3,8,9,7])

In [54]:
np.expand_dims(arr,axis=0)

array([[ 8, 14,  1,  8,  4,  7,  5,  3,  8,  9,  7]])

In [55]:
np.expand_dims(arr,axis=1)

array([[ 8],
       [14],
       [ 1],
       [ 8],
       [ 4],
       [ 7],
       [ 5],
       [ 3],
       [ 8],
       [ 9],
       [ 7]])

4. Squeeze

In [56]:
arr=np.array([[8],[14],[25],[5],[6],[7],[3]])

In [57]:
np.squeeze(arr)

array([ 8, 14, 25,  5,  6,  7,  3])

5. Count non-zero

In [58]:
a=np.array([0,0,1,1,1,0])

In [59]:
np.count_nonzero(a)

3

6. argwhere

In [62]:
a=np.array([0,0,1,1,1,0]) # it gives the indeces of non-zerp value

In [63]:
np.argwhere(a)

array([[2],
       [3],
       [4]], dtype=int64)

7. argmax and argmin

In [64]:
arr=np.array([[0.12,0.64,0.19,0.05]])

In [66]:
np.argmax(arr) #it gives the index value of the maximum value

1

In [68]:
np.argmin(arr) # it gives of minimum value

3

8. sorting

In [70]:
arr=np.array([2,3,1,7,4,5])

In [71]:
np.sort(arr)

array([1, 2, 3, 4, 5, 7])

9. Abs (absolute)

In [72]:
A=np.array([[1,-3,4],[-2,-4,3]])

In [73]:
np.abs(A)

array([[1, 3, 4],
       [2, 4, 3]])

10. ROund

In [74]:
a=np.random.random(size=(3,4))

In [75]:
a

array([[0.74045186, 0.32615276, 0.76742114, 0.92702066],
       [0.9320407 , 0.25928726, 0.40351395, 0.36465563],
       [0.02385262, 0.75296118, 0.44351546, 0.56328681]])

In [76]:
np.round(a,decimals=2)

array([[0.74, 0.33, 0.77, 0.93],
       [0.93, 0.26, 0.4 , 0.36],
       [0.02, 0.75, 0.44, 0.56]])

11. Clip

In [1]:
import numpy as np

In [2]:
arr=np.array([0,1,-3,-4,5,6,7,2,3])

In [3]:
arr.clip(0,5)

array([0, 1, 0, 0, 5, 5, 5, 2, 3])

In [4]:
arr.clip(0,3)

array([0, 1, 0, 0, 3, 3, 3, 2, 3])

12. Where

In [8]:
a=np.arange(12).reshape(4,3)  #np.where(condition,[x,y])
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
np.where(a>5)

(array([2, 2, 2, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

13.Put

In [10]:
#np.put(a,ind,v)

In [ ]:
np.put(arr,[1,2],[6,7])

In [13]:
arr

array([ 0,  6,  7, -4,  5,  6,  7,  2,  3])

14. Copyto

In [4]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print("Before arr1",arr1)
print("Before arr2",arr2)
np.copyto(arr1,arr2)
print("After arr1",arr1)
print("After arr2",arr2)

Before arr1 [1 2 3]
Before arr2 [4 5 6]
After arr1 [4 5 6]
After arr2 [4 5 6]


# Splitting

1. Horizontal split

In [10]:
A=np.array([[3,4,5,2],[6,7,2,6,]]) #splits the data into 2 equal parts
np.hsplit(A,2)

[array([[3, 4],
        [6, 7]]),
 array([[5, 2],
        [2, 6]])]

In [11]:
np.hsplit(A,4)

[array([[3],
        [6]]),
 array([[4],
        [7]]),
 array([[5],
        [2]]),
 array([[2],
        [6]])]

2.Vertical split

In [14]:
A=np.array([[3,4,5,2],[6,7,2,6]])
np.vsplit(A,2)

[array([[3, 4, 5, 2]]), array([[6, 7, 2, 6]])]

# Repeat

In [15]:
np.repeat('2017',3)

array(['2017', '2017', '2017'], dtype='<U4')

# Einsum

In [17]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(21,30).reshape(3,3)

In [19]:
np.einsum('ii->i',a) # extracts diagonal

array([1, 5, 9])

In [21]:
arr_2d=np.array([[1,2,3],[4,5,6]])
arr_1d=arr_2d.reshape(-1) #or
#arr_1d=arr_2d.ravel # ravel is equivalent to ii->i
print("Original 2D array:\n",arr_2d)
print("Reshaped 1D array:\n",arr_1d)

Original 2D array:
 [[1 2 3]
 [4 5 6]]
Reshaped 1D array:
 [1 2 3 4 5 6]


In [22]:
arr=np.array([[2,5,3],[5,6,3],[8,5,7]])

In [24]:
np.einsum('ji',arr)

array([[2, 5, 8],
       [5, 6, 5],
       [3, 3, 7]])

In [25]:
a=np.array([[4,7,2],[8,3,9],[7,1,4]])
b=np.array([[2,6,4],[9,5,1],[8,1,7]])

In [27]:
np.einsum('ij,jk',a,b) #matrix multiplication

array([[ 87,  61,  37],
       [115,  72,  98],
       [ 55,  51,  57]])

In [29]:
print(np.einsum('ii',a)) # sum of diagonal

11


# Histogram

In [32]:
A=np.array([[3,4,5,2],[6,7,2,6]]) #computes histogram values for a set of data
np.histogram(A)

(array([2, 0, 1, 0, 1, 0, 1, 0, 2, 1]),
 array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ]))